In [3]:
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 30 18:39:45 2020

@author: RAJARSI
"""

#%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from ipywidgets import interact
#----------------------------------------------------------------------
##  semi-block codes################
#----------------------------------------------------------------------
def initialstate(N):   
    ''' generates a random spin configuration for initial condition'''
    state =np.random.choice([-1, 1], size=(N, N))
    return state


def wolff(config):###wollff cluster implementation ## the followng is the function for a sngle run of cluster making and flipping.
   store=[]
   print(config)
   '''Monte Carlo move using Wolff-Cluster Sampling'''
   for i in range(50) :
       print('Loop No.',i)
       que = []  ### "que" ; stores the list of coordinates of the neighbours aded to the cluster
       (x0,y0) = np.random.randint(len(config)),np.random.randint(len(config)) ## a random spin is chosen at first
       que.append((x0,y0)) ## then added to the "que"
       
       
       while (len(que) > 0):## as mentioned in the documents I havesnt u , code must run untill there is nobody left to be added
           
               #print('Length of que ',len(que))
               
               q = que[np.random.randint(len(que))] ## a random element from que is chosen
               
               neighbours = [((q[0]+1)%N,q[1]), ((q[0]-1)%N,q[1]), (q[0],(q[1]+1)%N), (q[0],(q[1]-1)%N) ] ## neighbours to the selected spin are considered
               for c in neighbours:
                               
                   if all([config[q]==config[c]  , c not in que,np.random.rand() < p]):## process of adding spins to the que based on wolff's criteria if they have same spin
                      que.append(c)
               
                
               config[q] *= -1 ## the spin'q' that was selected from the que is flipped so to avoid being selected in future
               que.remove(q)  ## the spin'q' is removed from the 'que'
               j = i+1
               if(j%1 == 0):
                   #print(len(que))
                   store.append(config)
   
   #img= Image.fromarray(np.uint8((config + 1) * 0.5 * 255))  # 0 ... 255
   #img.show()                
   print(config)            
   return store

def display_spin_field(config):
    img= Image.fromarray(np.uint8((config + 1) * 0.5 * 255))  # 0 ... 255
    return img
    
    
def display_ising_sequence(images):
    def _show(frame=(0, len(images) - 1)):
        return display_spin_field(images[frame])
    return interact(_show)

#def control():
####################################
N = 100
kT = 1.5
J = 1
p = 1 - np.exp(-2*J/kT)


data=(wolff(initialstate(N)))
display_ising_sequence(data)

[[ 1 -1  1 ... -1  1  1]
 [-1 -1  1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1  1  1]
 ...
 [ 1  1 -1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1  1  1]
 [ 1 -1 -1 ... -1 -1 -1]]
Loop No. 0
Loop No. 1
Loop No. 2
Loop No. 3
Loop No. 4
Loop No. 5
Loop No. 6
Loop No. 7
Loop No. 8
Loop No. 9
Loop No. 10
Loop No. 11
Loop No. 12
Loop No. 13
Loop No. 14
Loop No. 15
Loop No. 16
Loop No. 17
Loop No. 18
Loop No. 19
Loop No. 20
Loop No. 21
Loop No. 22
Loop No. 23
Loop No. 24
Loop No. 25
Loop No. 26
Loop No. 27
Loop No. 28
Loop No. 29
Loop No. 30
Loop No. 31
Loop No. 32
Loop No. 33
Loop No. 34
Loop No. 35
Loop No. 36
Loop No. 37
Loop No. 38
Loop No. 39
Loop No. 40
Loop No. 41
Loop No. 42
Loop No. 43
Loop No. 44
Loop No. 45
Loop No. 46
Loop No. 47
Loop No. 48
Loop No. 49
[[ 1 -1  1 ... -1  1  1]
 [-1 -1  1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1  1  1]
 ...
 [ 1  1  1 ... -1 -1 -1]
 [ 1 -1  1 ... -1  1  1]
 [ 1 -1  1 ... -1 -1 -1]]


interactive(children=(IntSlider(value=543, description='frame', max=1086), Output()), _dom_classes=('widget-in…

<function __main__.display_ising_sequence.<locals>._show(frame=(0, 1086))>

In [36]:
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 30 18:39:45 2020

@author: RAJARSI
"""

#%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from ipywidgets import interact
import imageio
#----------------------------------------------------------------------
##  semi-block codes################
#----------------------------------------------------------------------
def initialstate(N):   
    ''' generates a random spin configuration for initial condition'''
    state =np.random.choice([-1, 1], size=(N, N))
    return state


def wolff(config):###wollff cluster implementation ## te followng is the function for a sngle run of cluster making and flipping.
    
   
   #print(config)
   '''Monte Carlo move using Wolff-Cluster Sampling'''
   #print('Loop No.',i)
   que = []  ### "que" ; stores the list of coordinates of the neighbours aded to the cluster
   (x0,y0) = np.random.randint(len(config)),np.random.randint(len(config)) ## a random spin is chosen at first
   que.append((x0,y0)) ## then added to the "que"


   while (len(que) > 0):## as mentioned in the documents I havesnt u , code must run untill there is nobody left to be added

       #print('Length of que ',len(que))

       q = que[np.random.randint(len(que))] ## a random element from que is chosen

       neighbours = [((q[0]+1)%N,q[1]), ((q[0]-1)%N,q[1]), (q[0],(q[1]+1)%N), (q[0],(q[1]-1)%N) ] ## neighbours to the selected spin are considered
       for c in neighbours:

           if all([config[q]==config[c]  , c not in que,np.random.rand() < p]):## process of adding spins to the que based on wolff's criteria if they have same spin
              que.append(c)


       config[q] *= -1 ## the spin'q' that was selected from the que is flipped so to avoid being selected in future
       que.remove(q)  ## the spin'q' is removed from the 'que'
       
   return config

def display_spin_field(config):
    return Image.fromarray(np.uint8((config + 1) * 0.5 * 255))  # 0 ... 255
    
    
    
def display_ising_sequence(images):
    def _show(frame=(0, len(images) - 1)):
        return display_spin_field(images[frame])
    return interact(_show)

#def control():
####################################
N = 100       #N X N spin field
kT = 1.5
J = 1
p = 1 - np.exp(-2*J/kT)



images = [initialstate(N)]
for i in range(130):                         # No.of loops you want 
    if (i%10==0):
        print ('Completed',i,'loops')
    images.append(wolff(images[-1].copy()))
display_ising_sequence(images);

imageio.mimsave('E:\Project\movie.gif', np.uint8(images), format='gif', fps=8)

Completed 0 loops
Completed 10 loops
Completed 20 loops
Completed 30 loops
Completed 40 loops
Completed 50 loops
Completed 60 loops
Completed 70 loops
Completed 80 loops
Completed 90 loops
Completed 100 loops
Completed 110 loops
Completed 120 loops


interactive(children=(IntSlider(value=65, description='frame', max=130), Output()), _dom_classes=('widget-inte…